name: Sample actions

on:
  push:
    branches: main # mainブランチの場合はmainに変更
  pull_request:

jobs:
  hogehoge:
    runs-on: ubuntu-latest # 実行環境の設定

    steps:
    - uses: actions/checkout@master
    - name: GitHub Action for pylint
      uses: cclauss/GitHub-Action-for-pylint@master